# Problems for Daily Bug Hunt: short enough that Ciel's solution fits in
# 10-20 lines (spec section 3). Separate from `exercises_seed.py` - those
# problems are sized for full graded exercises, not a 2-5 minute daily game.
DAILY_PROMPTS: list[str] = [
    "Kiem tra mot so co phai so nguyen to",
    "Tim phan tu xuat hien nhieu nhat trong danh sach",
    "Dao nguoc mot chuoi",
    "Tinh tong N so Fibonacci dau tien",
    "Kiem tra chuoi co phai palindrome",
    "Tim so lon thu hai trong danh sach",
    "Dem so nguyen am trong danh sach",
    "Loai bo phan tu trung lap khoi danh sach, giu thu tu",
    "Tim uoc chung lon nhat cua hai so",
    "Kiem tra hai chuoi co phai la anagram",
    "Tinh giai thua cua mot so",
    "Tim phan tu con thieu trong day so lien tiep",
    "Dem so lan xuat hien cua moi ky tu trong chuoi",
    "Tim cap so trong danh sach co tong bang target",
    "Sap xep danh sach bang bubble sort",
    "Tim chuoi con dai nhat khong lap ky tu",
    "Kiem tra ngoac don co can bang khong",
    "Tinh trung binh cong bo qua gia tri am",
    "Tim phan tu xuat hien dung 1 lan trong danh sach co phan tu lap",
    "Chuyen so nguyen sang chuoi nhi phan",
    "Tinh so ngay giua hai moc thoi gian",
    "Gop hai danh sach da sap xep thanh mot danh sach sap xep",
    "Tim phan tu nho nhat trong danh sach da sap xep va xoay vong",
    "Dem so buoc de leo het cau thang (climbing stairs)",
    "Tim subarray lien tiep co tong lon nhat (Kadane)",
    "Kiem tra mot ma tran vuong co doi xung qua duong cheo khong",
    "Tim k phan tu lon nhat trong danh sach",
    "Nhom cac tu la anagram cua nhau",
    "Tinh khoang cach Levenshtein don gian giua hai chuoi ngan",
    "Tim phan tu chung giua hai danh sach",
]
